### ISSUE TITLE
[Bug] Sometimes layers don't move back on CTRL+Z

### ISSUE THREAD

**Issue by turesiht** [aseprite/aseprite#3365]
When I move the layer something happens and I can't move it back with ctrl+z, it just goes through previous history
I wasn't able to reproduce it but I've encountered it several times already.
### Aseprite and System version

* Aseprite version: 1.3-beta16-x64, Steam
* System: Windows 10

**Comment by dacap** [comment]
Hi @turesiht, do you move the layer with the move tool (Ctrl+drag and drop, or V key), or transforming the selection?

When we transform the selection only the first position and the last position of the whole transformation will be stored in the undo. This might be related to #424 and #1459

**Comment by turesiht** [comment]
I use ctrl+drag and drop

**Comment by dacap** [comment]
Probably fixed in latest release with https://github.com/aseprite/aseprite/commit/9a3958278baa6d0f5e87070f1bb179dda3d8d9cf and related to #3416

**Comment by turesiht** [comment]
Still having this issue. Not exactly sure what causes this, I feel pressing several keys quickly or simultaneously. Will continue to test
