### ISSUE TITLE
Reduce lag on cursor movement (mac)

### ISSUE THREAD

**Issue by HawkenKing** [aseprite/aseprite#926]
Currently the lag on cursor movement in Aseprite on mac is very noticeable. It's ok for smaller canvases but for larger projects this can be a impedance to workflow.

Ideal lag would be something similar to Photoshop, where it is not noticeable.

**Comment by dacap** [comment]
It should be fixed with #139

**Comment by dacap** [comment]
Hi @HawkenKing, would you like to contact me at support@aseprite.org about this issue.

**Comment by dacap** [comment]
It should already fixed with the new Skia back-end.

**Comment by Segmented** [comment]
I still experience lag from cursor movement on OSX 10.10.5 with v1.1.9.

**Comment by dacap** [comment]
@Segmented hi! could you please check if using the **Simple Crosshair** in preferences does it help?

![screen shot 2016-11-15 at 10 15 42 am](https://cloud.githubusercontent.com/assets/39654/20307085/8f661ebe-ab1c-11e6-945a-53049d4fb8d7.png)

**Comment by Segmented** [comment]
Yep that helps thanks! Perhaps that should be a default setting on the mac.

**Comment by thetrung** [comment]
Until 1.2.6 version, I still encounter this :| So, thanks to this thread !
